### ISSUE TITLE
Layout básico e crud de projetos

### ISSUE THREAD

**Issue by elton182** [brasil-php/project-manager#9]
- [x] Criar layout básico com vuetify
- [x] Criar o primeiro crud para o crud de projetos
- [x] Data-table com search no server-side

**Comment by IgorDePaula** [comment]
@elton182, se olhar as rotas API, o crud ja esta pronto (inclusive na pasta de testes). Falta apenas criar os forms e as rotas para os forms.

**Comment by elton182** [comment]
@IgorDePaula eu notei, ta com resource lá.

O que estou pensando em fazer é o data-table ser no backend (search e pagination), já pensando em performance

**Comment by IgorDePaula** [comment]
https://github.com/brasil-php/project-manager/blob/master/app/Http/Controllers/Api/ProjectController.php#L19

Já tem, só precisa da tela mesmo =D

**Comment by elton182** [comment]
fiz um bem bolado aqui.. da uma olhada
